name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  graphql_generator:
    path: ..

dev_dependencies:
  build_runner: ^1.1.3

flutter:
  uses-material-design: true