# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  # name of the builder
  graph_ql:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:graphql_generator/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["generateGraphQLBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart": [".graphql.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source