name: graphql_generator
description: A library to generate the model class for GraphQL query.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: any
  http: ^0.12.0+1
  code_builder: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: