name: graphql_generator
description: A library to generate the model class for GraphQL query.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  source_gen: any
  http: ^0.12.0+1
  code_builder: ^3.2.0
  json_annotation: ^2.0.0
  test: ^1.5.3

dev_dependencies:
  json_serializable: ^2.0.0
  build_runner: ^1.1.3

flutter: